stages:
  - build
  - test

variables:
  TEST_RESULT: "success"

build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - echo "Running tests..."
    - pytest > result.log; tail -n 10 result.log
    - echo "TEST_RESULT=$TEST_RESULT" >> .env

after_script:
  - echo "Test result is $TEST_RESULT"