name: CI Workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          pytest > result.log; tail -n 10 result.log

      # Étape 5 : Définir une variable d'environnement au lieu de `set-output`
      - name: Set test result as environment variable
        id: set_output
        run: echo "test_result=success" >> $GITHUB_ENV

      # Étape 6 : Afficher la valeur de la variable (facultatif)
      - name: Display test result
        run: echo "Test result is ${{ env.test_result }}"